# Use the official NGINX image as the base
FROM nginx:latest

# Copy the static HTML file into the container
COPY index.html /usr/share/nginx/html/

# Expose port 80 for the container
#EXPOSE 80

# Start NGINX
#CMD ["nginx", "-g", "daemon off;"]

